#!/bin/sh -x
#PJM -L  "freq=2200"
#PJM -L  "node=1"
#PJM --mpi "shape=1"
#PJM -L  "rscgrp=small-s1,eco_state=2"
#PJM -L  "elapse=00:20:00"
#PJM --mpi "max-proc-per-node=4"
#PJM -g hp230257
#PJM -s
#
# 8x12x8=768
# 12x15x12=2160
# 16x24x16=6144
# 24x32x24=18432
# 32x36x32=36864
# 36x36x36=46656

export OMP_NUM_THREADS=12
# /vol0004/apps/oss/spack-v0.21/opt/spack/linux-rhel8-a64fx/fj-4.10.0/hdf5-1.10.11-zpd2xhosz2bamf5pewxpjxqzkvbf567i
# export LD_LIBRARY_PATH=../../../OPENBLAS/lib:$LD_LIBRARY_PATH
# export tensorflow_root=../TEST_TF/tensorflow-2.2.0-cc
# export CPATH=$tensorflow_root/include:$CPATH
# export LD_LIBRARY_PATH=$tensorflow_root/lib:$LD_LIBRARY_PATH

export OPENBLAS_NUM_THREADS=1

export COMM_OMP_FLAG=0
export COMM_BORDER_ONE_FLAG=1
export COMM_PIGGY_FLAG=1
export THREAD_POOL_FLAG=1
export COMM_DEBUG_FLAG=0

export TABULATE_FLAG=5
mpiexec ./lmp_execute_double  -in ./in.deepmd_accuracy_fp64                          # Execute a.out

export TABULATE_FLAG=5
mpiexec ./lmp_execute_cblas  -in ./in.deepmd_accuracy_fp16                          # Execute a.out

export TABULATE_FLAG=5
mpiexec ./lmp_execute_float  -in ./in.deepmd_accuracy_fp16                          # Execute a.out

export TABULATE_FLAG=1
mpiexec ./lmp_execute_float  -in ./in.deepmd_accuracy_fp16_v0001                          # Execute a.out


export TABULATE_FLAG=5
mpiexec -np 1 ./lmp_execute_double  -in ./in.deepmd_speed_v01    -l log_double.log                       # Execute a.out
sleep 1
mpiexec -np 1 ./lmp_execute_double  -in ./in.deepmd_speed_v01    -l log_double.log                     # Execute a.out
sleep 1
export TABULATE_FLAG=5
mpiexec -np 1 ./lmp_execute_cblas  -in ./in.deepmd_speed_v01     -l log_cblas.log                     # Execute a.out
sleep 1
mpiexec -np 1 ./lmp_execute_cblas  -in ./in.deepmd_speed_v01     -l log_cblas.log                     # Execute a.out
sleep 1

export TABULATE_FLAG=5
mpiexec -np 1 ./lmp_execute_float  -in ./in.deepmd_speed_v01    -l log_float.log                      # Execute a.out
sleep 1
mpiexec -np 1 ./lmp_execute_float  -in ./in.deepmd_speed_v01    -l log_float.log                      # Execute a.out
sleep 1

export TABULATE_FLAG=1
mpiexec -np 1 ./lmp_execute_float  -in ./in.deepmd_speed_v0001   -l log_float_v0001.log                       # Execute a.out
sleep 1
mpiexec -np 1 ./lmp_execute_float  -in ./in.deepmd_speed_v0001   -l log_float_v0001.log                       # Execute a.out
sleep 1
